import { Institution } from "./interfaces";

  
  export const institutions: Institution[] = [
    {
      id: 1,
      name: 'IIT Madras - Indian Institute of Technology [IITM], Chennai',
      courseFees: 2200,
      placementFees: 100000,
      reviews: '8.6/10',
      ranking: '#3rd/131 in India',
    },
    {
      id: 2,
      name: 'IIT Delhi - Indian Institute of Technology [IITD], New Delhi',
      courseFees: 2500,
      placementFees: 95000,
      reviews: '8.8/10',
      ranking: '#2nd/131 in India',
    },
    {
      id: 3,
      name: 'IIT Bombay - Indian Institute of Technology [IITB], Mumbai',
      courseFees: 2700,
      placementFees: 98000,
      reviews: '9.0/10',
      ranking: '#1st/131 in India',
    },
    {
      id: 4,
      name: 'IIT Kanpur - Indian Institute of Technology [IITK], Kanpur',
      courseFees: 2400,
      placementFees: 92000,
      reviews: '8.7/10',
      ranking: '#4th/131 in India',
    },
    {
      id: 5,
      name: 'IIT Kharagpur - Indian Institute of Technology [IITKGP], Kharagpur',
      courseFees: 2100,
      placementFees: 91000,
      reviews: '8.5/10',
      ranking: '#5th/131 in India',
    },
    {
      id: 6,
      name: 'IIT Roorkee - Indian Institute of Technology [IITR], Roorkee',
      courseFees: 2300,
      placementFees: 93000,
      reviews: '8.4/10',
      ranking: '#6th/131 in India',
    },
    {
      id: 7,
      name: 'IIT Guwahati - Indian Institute of Technology [IITG], Guwahati',
      courseFees: 2200,
      placementFees: 88000,
      reviews: '8.2/10',
      ranking: '#7th/131 in India',
    },
    {
      id: 8,
      name: 'IIT Hyderabad - Indian Institute of Technology [IITH], Hyderabad',
      courseFees: 2600,
      placementFees: 89000,
      reviews: '8.3/10',
      ranking: '#8th/131 in India',
    },
    {
      id: 9,
      name: 'NIT Trichy - National Institute of Technology [NITT], Trichy',
      courseFees: 1500,
      placementFees: 75000,
      reviews: '8.0/10',
      ranking: '#9th/131 in India',
    },
    {
      id: 10,
      name: 'NIT Surathkal - National Institute of Technology [NITK], Surathkal',
      courseFees: 1600,
      placementFees: 77000,
      reviews: '7.9/10',
      ranking: '#10th/131 in India',
    },
    {
      id: 11,
      name: 'IIT Indore - Indian Institute of Technology [IITI], Indore',
      courseFees: 2300,
      placementFees: 85000,
      reviews: '7.8/10',
      ranking: '#11th/131 in India',
    },
    {
      id: 12,
      name: 'BITS Pilani - Birla Institute of Technology and Science, Pilani',
      courseFees: 3200,
      placementFees: 92000,
      reviews: '9.2/10',
      ranking: '#12th/131 in India',
    },
    {
      id: 13,
      name: 'IIT Bhubaneswar - Indian Institute of Technology [IITBBS], Bhubaneswar',
      courseFees: 2400,
      placementFees: 87000,
      reviews: '7.7/10',
      ranking: '#13th/131 in India',
    },
    {
      id: 14,
      name: 'IIT Patna - Indian Institute of Technology [IITP], Patna',
      courseFees: 2200,
      placementFees: 86000,
      reviews: '7.6/10',
      ranking: '#14th/131 in India',
    },
    {
      id: 15,
      name: 'IIT Mandi - Indian Institute of Technology [IITMandi], Mandi',
      courseFees: 2100,
      placementFees: 80000,
      reviews: '7.5/10',
      ranking: '#15th/131 in India',
    }
  ];
  